<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Pei Hsin Lin" />


<title>Predict for Score</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="final_report.html">Report</a>
</li>
<li>
  <a href="eda.html">Data Exploration</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="MLR_nwins.html">Regression for playoff</a>
    </li>
    <li>
      <a href="second_regression.html">Regression for win or lose</a>
    </li>
    <li>
      <a href="regresssion_for_score.html">Regression for score</a>
    </li>
  </ul>
</li>
<li>
  <a href="knicks_in_21.html">Knicks in New Season</a>
</li>
<li>
  <a href="https://jessiegao.shinyapps.io/shiny_app/">Shiny App</a>
</li>
<li>
  <a href="proposal.html">About</a>
</li>
<li>
  <a href="https://github.com/YucongGao/help_knicks_to_playoff.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fab fa-linkedin"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://www.linkedin.com/in/yucong-gao/">Jessie Gao</a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/seanyangds/">Sean Yang</a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/hao-zheng-606848225">Hazel Zheng</a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/pei-hsin-lin-299aa821b">Peggy Lin</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Predict for Score</h1>
<h4 class="author">Pei Hsin Lin</h4>
<h4 class="date">12/8/2021</h4>

</div>


<style type="text/css">

h1.title {
  text-align: center;
}

</style>
<pre class="r"><code>knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = &quot;90%&quot;
)

theme_set(theme_minimal() + theme(legend.position = &quot;bottom&quot;))

options(
  ggplot2.continuous.colour = &quot;viridis&quot;,
  ggplot2.continuous.fill = &quot;viridis&quot;
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d</code></pre>
<div id="data" class="section level2">
<h2>Data</h2>
<pre class="r"><code>box_score_all = read_csv(&quot;./data2/box_score_all.csv&quot;)</code></pre>
<pre><code>## Rows: 47830 Columns: 30</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr   (6): season_year, team_abbreviation, team_name, game_id, matchup, wl
## dbl  (23): team_id, min, fgm, fga, fg_pct, fg3m, fg3a, fg3_pct, ftm, fta, ft...
## dttm  (1): game_date</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>regre_df = 
  box_score_all %&gt;%
  select(-c(1:7)) %&gt;%
  select(-ends_with(&quot;rank&quot;)) %&gt;%
  mutate(wl = recode(wl, &quot;W&quot; = 1, &quot;L&quot; = 0),
         wl = as.factor(wl)) </code></pre>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<div id="variable-description" class="section level3">
<h3>Variable description</h3>
<p>After ruling out variables with strong correlation, we include variables as follow: Dependent variable is the score of each game, denoted by pts (points). Independent variables are selected from both <strong>offensive</strong> aspect and <strong>defensive</strong> aspect.</p>
<p>For the offensive level, variables include:</p>
<ul>
<li>fg3_pct: proportion of three points shooting</li>
<li>fg_pct: proportion of field goals attempted</li>
<li>fg_pct: proportion of free throw</li>
<li>oreb: average offensive rebounds per game</li>
<li>ast: average assists per games</li>
</ul>
<p>As for the defensive level, variables include:</p>
<ul>
<li>stl: steals of each game</li>
<li>blk: blocks of each game</li>
<li>dreb: defensive rebounds of each game</li>
<li>tov: turnovers of each game</li>
<li>pf: personal foul of each game</li>
</ul>
</div>
<div id="modelling" class="section level3">
<h3>Modelling</h3>
<p>Use step function to choose a model by AIC in a Stepwise algorithm.</p>
<pre class="r"><code>ln_regre = lm(pts ~fg_pct+fg3_pct+ft_pct+oreb+dreb+ast+stl+blk+tov+pf,data = regre_df)
summary(ln_regre)</code></pre>
<pre><code>## 
## Call:
## lm(formula = pts ~ fg_pct + fg3_pct + ft_pct + oreb + dreb + 
##     ast + stl + blk + tov + pf, data = regre_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.617  -5.038  -0.342   4.710  46.223 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -25.229423   0.515913  -48.90   &lt;2e-16 ***
## fg_pct      138.594897   0.803307  172.53   &lt;2e-16 ***
## fg3_pct      14.564180   0.325892   44.69   &lt;2e-16 ***
## ft_pct       24.290515   0.331887   73.19   &lt;2e-16 ***
## oreb          0.802525   0.009228   86.96   &lt;2e-16 ***
## dreb          0.563889   0.006492   86.86   &lt;2e-16 ***
## ast           0.487421   0.008136   59.91   &lt;2e-16 ***
## stl           0.565725   0.011870   47.66   &lt;2e-16 ***
## blk          -0.152531   0.013351  -11.43   &lt;2e-16 ***
## tov          -0.682900   0.008899  -76.74   &lt;2e-16 ***
## pf            0.404912   0.007667   52.81   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.334 on 47819 degrees of freedom
## Multiple R-squared:  0.6916, Adjusted R-squared:  0.6916 
## F-statistic: 1.072e+04 on 10 and 47819 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>linear.step = step(ln_regre,direction=&quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=190616
## pts ~ fg_pct + fg3_pct + ft_pct + oreb + dreb + ast + stl + blk + 
##     tov + pf
## 
##           Df Sum of Sq     RSS    AIC
## &lt;none&gt;                 2572088 190616
## - blk      1      7021 2579109 190744
## - fg3_pct  1    107426 2679514 192571
## - stl      1    122170 2694258 192834
## - pf       1    150024 2722112 193325
## - ast      1    193050 2765138 194076
## - ft_pct   1    288123 2860211 195692
## - tov      1    316762 2888850 196169
## - dreb     1    405789 2977877 197621
## - oreb     1    406778 2978867 197637
## - fg_pct   1   1601094 4173182 213762</code></pre>
<pre class="r"><code>summary(linear.step)</code></pre>
<pre><code>## 
## Call:
## lm(formula = pts ~ fg_pct + fg3_pct + ft_pct + oreb + dreb + 
##     ast + stl + blk + tov + pf, data = regre_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.617  -5.038  -0.342   4.710  46.223 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -25.229423   0.515913  -48.90   &lt;2e-16 ***
## fg_pct      138.594897   0.803307  172.53   &lt;2e-16 ***
## fg3_pct      14.564180   0.325892   44.69   &lt;2e-16 ***
## ft_pct       24.290515   0.331887   73.19   &lt;2e-16 ***
## oreb          0.802525   0.009228   86.96   &lt;2e-16 ***
## dreb          0.563889   0.006492   86.86   &lt;2e-16 ***
## ast           0.487421   0.008136   59.91   &lt;2e-16 ***
## stl           0.565725   0.011870   47.66   &lt;2e-16 ***
## blk          -0.152531   0.013351  -11.43   &lt;2e-16 ***
## tov          -0.682900   0.008899  -76.74   &lt;2e-16 ***
## pf            0.404912   0.007667   52.81   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.334 on 47819 degrees of freedom
## Multiple R-squared:  0.6916, Adjusted R-squared:  0.6916 
## F-statistic: 1.072e+04 on 10 and 47819 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The adjusted R square for the full model is 0.6916, that is to say 69.16% of variances in the response variable can be explained by the predictors.</p>
</div>
<div id="model-diagnostic" class="section level3">
<h3>Model diagnostic</h3>
<p>1). to check if the error term is normally distributed with mean 0.</p>
<pre class="r"><code>ggplot(data = ln_regre , aes(x = ln_regre$residuals)) + geom_histogram()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="regresssion_for_score-_files/figure-html/unnamed-chunk-6-1.png" width="90%" /></p>
<p>Condition 1 is met.</p>
<p>2). to check if the error term is independent of the dependent variable.</p>
<pre class="r"><code>ggplot(data = ln_regre, aes(x = ln_regre$fitted.values, y = ln_regre$residuals)) + geom_point() + geom_smooth(method = &quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="regresssion_for_score-_files/figure-html/unnamed-chunk-7-1.png" width="90%" /></p>
<p>Condition 2 is met as we cannot see an obvious tendency of errors.</p>
</div>
<div id="interpretation-of-model-coefficients" class="section level3">
<h3>Interpretation of model coefficients</h3>
<p>According to model ln_regre,the equation will look like this. <img src="image/second_linear_regre.jpeg" /></p>
<p>All variables selected are significant in this linear regression model.</p>
<p>For each additional 0.1 of proportion of field goals attempted, the points will increase 13.9.</p>
<p>For each additional 0.1 of proportion three points shooting, the points will increase 1.45.</p>
<p>For each additional 0.1 of proportion of free throw, the points will increase 2.43.</p>
<p>For each additional 1 of offensive rebounds per game, the points will increase 0.8.</p>
<p>For each additional 1 of defensive rebounds per games, the points will increase 0.56.</p>
<p>For each additional 1 of steals per game, the points will increase 0.57.</p>
<p>For each additional 1 of assists per game, the points will increase 0.45.</p>
<p>For each additional 1 of blocks per game, the points will decrease 0.15.</p>
<p>For each additional 1 of turnovers per game, the points will decrease 0.68.</p>
<p>For each additional 1 of personal foul per game, the points will decrease 0.4.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
